//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolKids.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IPCameraResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IPCameraResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoolKids.Common.Resources.IPCameraResources", typeof(IPCameraResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Camera.
        /// </summary>
        public static string AddCameraTab {
            get {
                return ResourceManager.GetString("AddCameraTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddToLockScreen {
            get {
                return ResourceManager.GetString("AddToLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string AdvancedTab {
            get {
                return ResourceManager.GetString("AdvancedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarMenuItemAbout {
            get {
                return ResourceManager.GetString("AppBarMenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarMenuItemSettings {
            get {
                return ResourceManager.GetString("AppBarMenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP CAM ULTIMATE.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update In Background.
        /// </summary>
        public static string AutomaticallyUpdateTile {
            get {
                return ResourceManager.GetString("AutomaticallyUpdateTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This camera has already been pinned to your start screen..
        /// </summary>
        public static string CameraAlreadyPinned {
            get {
                return ResourceManager.GetString("CameraAlreadyPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Set to Lock Screen.
        /// </summary>
        public static string CameraImageSetToLockScreen {
            get {
                return ResourceManager.GetString("CameraImageSetToLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Manufacture.
        /// </summary>
        public static string CameraMfg {
            get {
                return ResourceManager.GetString("CameraMfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Model.
        /// </summary>
        public static string CameraModel {
            get {
                return ResourceManager.GetString("CameraModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Name.
        /// </summary>
        public static string CameraName {
            get {
                return ResourceManager.GetString("CameraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Name is Required.
        /// </summary>
        public static string CameraNameIsRequired {
            get {
                return ResourceManager.GetString("CameraNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to patrol.
        /// </summary>
        public static string CameraPatrol {
            get {
                return ResourceManager.GetString("CameraPatrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to presets.
        /// </summary>
        public static string CameraPresets {
            get {
                return ResourceManager.GetString("CameraPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string CameraPreviewTab {
            get {
                return ResourceManager.GetString("CameraPreviewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera URL.
        /// </summary>
        public static string CameraUrl {
            get {
                return ResourceManager.GetString("CameraUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we are having a difficult time connecting to your IP Camera, would you like to see our trouble shooting tips?.
        /// </summary>
        public static string CanNotConnectMessage {
            get {
                return ResourceManager.GetString("CanNotConnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Defaults.
        /// </summary>
        public static string ClearDefaults {
            get {
                return ResourceManager.GetString("ClearDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Lock Screen.
        /// </summary>
        public static string ConfigureLockScreen {
            get {
                return ResourceManager.GetString("ConfigureLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        public static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Connect.
        /// </summary>
        public static string CouldNotConnectTitle {
            get {
                return ResourceManager.GetString("CouldNotConnectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By: .
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defaults.
        /// </summary>
        public static string Defaults {
            get {
                return ResourceManager.GetString("Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preset names.
        /// </summary>
        public static string EditPresetNames {
            get {
                return ResourceManager.GetString("EditPresetNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Lables.
        /// </summary>
        public static string EditPresetNamesMenu {
            get {
                return ResourceManager.GetString("EditPresetNamesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was an error connecting to your camera, please try again later..
        /// </summary>
        public static string ErrorConnectingToCamera {
            get {
                return ResourceManager.GetString("ErrorConnectingToCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string FinishTab {
            get {
                return ResourceManager.GetString("FinishTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip.
        /// </summary>
        public static string Flip {
            get {
                return ResourceManager.GetString("Flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Preset.
        /// </summary>
        public static string GotoPreset {
            get {
                return ResourceManager.GetString("GotoPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Tilt Controls.
        /// </summary>
        public static string InvertTiltControls {
            get {
                return ResourceManager.GetString("InvertTiltControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my cameras.
        /// </summary>
        public static string MainScreenName {
            get {
                return ResourceManager.GetString("MainScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MJPEG Decoder - Brian Peek.
        /// </summary>
        public static string MJpegdecoder {
            get {
                return ResourceManager.GetString("MJpegdecoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There does not appear to be an internet connection. Please try again later..
        /// </summary>
        public static string NoInternetMessage {
            get {
                return ResourceManager.GetString("NoInternetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Now.
        /// </summary>
        public static string NotNow {
            get {
                return ResourceManager.GetString("NotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Help.
        /// </summary>
        public static string OnlineHelp {
            get {
                return ResourceManager.GetString("OnlineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (optional).
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string PortNumber {
            get {
                return ResourceManager.GetString("PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your port number must be between 1 and 65535.
        /// </summary>
        public static string PortNumberBetween1And100 {
            get {
                return ResourceManager.GetString("PortNumberBetween1And100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Picture Ready.
        /// </summary>
        public static string PreparingImage {
            get {
                return ResourceManager.GetString("PreparingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Five.
        /// </summary>
        public static string PresetFive {
            get {
                return ResourceManager.GetString("PresetFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Four.
        /// </summary>
        public static string PresetFour {
            get {
                return ResourceManager.GetString("PresetFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset One.
        /// </summary>
        public static string PresetOne {
            get {
                return ResourceManager.GetString("PresetOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Six.
        /// </summary>
        public static string PresetSix {
            get {
                return ResourceManager.GetString("PresetSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Three.
        /// </summary>
        public static string PresetThree {
            get {
                return ResourceManager.GetString("PresetThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Two.
        /// </summary>
        public static string PresetTwo {
            get {
                return ResourceManager.GetString("PresetTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Options.
        /// </summary>
        public static string PurchaseOptions {
            get {
                return ResourceManager.GetString("PurchaseOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** Rate This App **.
        /// </summary>
        public static string RateApp {
            get {
                return ResourceManager.GetString("RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for clicking on Rate This App..
        /// </summary>
        public static string RatingMessage {
            get {
                return ResourceManager.GetString("RatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Support.
        /// </summary>
        public static string RequestSupport {
            get {
                return ResourceManager.GetString("RequestSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If after completing the above steps and you still can&apos;t connect to your camera, please use the form below to request support.  .
        /// </summary>
        public static string RequestSupportHeader {
            get {
                return ResourceManager.GetString("RequestSupportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Defaults.
        /// </summary>
        public static string SaveDefaults {
            get {
                return ResourceManager.GetString("SaveDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Camera.
        /// </summary>
        public static string SaveNewCamera {
            get {
                return ResourceManager.GetString("SaveNewCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your URL, User Name and Password to make setting up other cameras quicker?.
        /// </summary>
        public static string SaveSettingsByDefault {
            get {
                return ResourceManager.GetString("SaveSettingsByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Developer.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Feedback.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Preset.
        /// </summary>
        public static string SetPreset {
            get {
                return ResourceManager.GetString("SetPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageName {
            get {
                return ResourceManager.GetString("SettingsPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing the rating process is on the honor system and your additional camera license will be added upon return to our app..
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please also understand that while we strive to support as many IP cameras as possible, we prioritize development support based upon feedback.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Pan/Tilt.
        /// </summary>
        public static string SupportPanTilt {
            get {
                return ResourceManager.GetString("SupportPanTilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support.
        /// </summary>
        public static string TroubleShooting {
            get {
                return ResourceManager.GetString("TroubleShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry you are having problems connecting to your IP Camera.  The developers at IP Cam Ultimate strive to support as many cameras as possible..
        /// </summary>
        public static string TroubleShootingIntro {
            get {
                return ResourceManager.GetString("TroubleShootingIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First ensure that you can connect to your IP camera through a browser or the application that came with your camera..
        /// </summary>
        public static string TroubleShootingStep1 {
            get {
                return ResourceManager.GetString("TroubleShootingStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you can connect, are you connecting outside of your house? If not you may need to make your camera available on the internet..
        /// </summary>
        public static string TroubleShootingStep2 {
            get {
                return ResourceManager.GetString("TroubleShootingStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Controls - Component One.
        /// </summary>
        public static string UIControls {
            get {
                return ResourceManager.GetString("UIControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        public static string Unlimited {
            get {
                return ResourceManager.GetString("Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update in Background.
        /// </summary>
        public static string UpdateTileInBackground {
            get {
                return ResourceManager.GetString("UpdateTileInBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this option if you would like to have your cameras up date your application, live tiles and lock screen in the background (if enabled)..
        /// </summary>
        public static string UpdatingInBackground {
            get {
                return ResourceManager.GetString("UpdatingInBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Mode.
        /// </summary>
        public static string UserMode {
            get {
                return ResourceManager.GetString("UserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string UserModeAdmin {
            get {
                return ResourceManager.GetString("UserModeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string UserModeGuest {
            get {
                return ResourceManager.GetString("UserModeGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string UserModeOperator {
            get {
                return ResourceManager.GetString("UserModeOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Three Additional.
        /// </summary>
        public static string View3Cameras {
            get {
                return ResourceManager.GetString("View3Cameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewable Cameras:.
        /// </summary>
        public static string ViewableCameras {
            get {
                return ResourceManager.GetString("ViewableCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view more.
        /// </summary>
        public static string ViewAdditionalCameras {
            get {
                return ResourceManager.GetString("ViewAdditionalCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view one camera for FREE and can view an additional one for free, by rating the app..
        /// </summary>
        public static string ViewMoreInstructionsOne {
            get {
                return ResourceManager.GetString("ViewMoreInstructionsOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To help support further development of this app, you can purchase packages to view additional cameras..
        /// </summary>
        public static string ViewMoreInstructionsTwo {
            get {
                return ResourceManager.GetString("ViewMoreInstructionsTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Unlimited.
        /// </summary>
        public static string ViewUnlimitedCameras {
            get {
                return ResourceManager.GetString("ViewUnlimitedCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License: {0} camera(s)..
        /// </summary>
        public static string YouCanView {
            get {
                return ResourceManager.GetString("YouCanView", resourceCulture);
            }
        }
    }
}
